/*rightMidX=;
  rightMidY=;
  rightMidWidth=;
  rightMidHeight=;
  //RightMid
  rightLowX=;
  rightLowY=;
  rightLowWidth=;
 rightLowHeight=;
  //RightLow
  midTopX=;
  midTopY=;
  midTopWidth=;
  midTopHeight=;
  //MidTop
  midCenterX=xCenter-appWidth/6;
  midCenterY=yCenter-appHeight/6;
  midCenterWidth=;
  midCenterHeight=;
  //MidCenter
  midLowX=;
  midLowY=;
  midLowWidth=;
  midLowHeight=;
  //midLow
  leftTopX=;
  leftTopY=;
  leftTopWidth=;
  leftTopHeight=;
  //LeftTop
  leftMidX=;
  leftMidY=;
  leftMidWidth=;
  leftMidHeight=;
  //LeftMid
  leftLowX=;
  leftLowY=;
  leftLowWidth=;
  leftLowHeight=;
  //LeftMid
  */
  
